import { theme } from "./theme.js";

export function wrapLayout(innerHtml: string, date: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Morning Brief — ${escapeHtml(date)}</title>
</head>
<body style="margin:0;padding:0;background-color:#f0f2f5;font-family:${theme.fontFamily};">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" role="presentation">
    <tr>
      <td align="center" style="padding:32px 16px 40px;">
        <table width="${theme.maxWidth}" cellpadding="0" cellspacing="0" border="0" role="presentation"
               style="max-width:${theme.maxWidth};width:100%;background-color:${theme.colors.bg};border-radius:16px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08);">
          ${innerHtml}
          <tr>
            <td style="padding:24px;text-align:center;border-top:1px solid ${theme.colors.border};">
              <p style="margin:0;font-size:11px;color:${theme.colors.textMuted};">
                Generated by your Boop agent · ${escapeHtml(date)}
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
